set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g mouse on
set -g history-limit 100000
set -g escape-time 10
set -g renumber-windows on
set -g allow-rename off
set -g set-clipboard on
setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
