#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff
# normal_window_opacity        0.95           \
    padding=6
# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.1            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.1            \
    active_window_opacity        1.0            \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  $padding       \
    bottom_padding               $padding       \
    left_padding                 $padding       \
    right_padding                $padding       \
    window_gap                   $padding       \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

borders active_color=0x50ceffce inactive_color=0x00000000 width=4.0 &

# rules
yabai -m rule --add app="^Arc$" title="^Space [0-9]+$" grid=12:8:2:2:4:3 manage=off
yabai -m rule --add app="^Arc$" title="^jweaker$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Clock$" manage=off
