#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff

# global settings
yabai -m config window_opacity               off
yabai -m config window_topmost               on
yabai -m config window_shadow                float
# yabai -m config auto_balance                 on

# border settings
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff8E83B8
yabai -m config normal_window_border_color   0xff51425C

# mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabae -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add title="^About$" manage=off

echo "yabai configuration loaded.."
